name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pester:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # PR head 取得テストの将来拡張に備え全履歴

      - name: Ensure PowerShell
        shell: pwsh
        run: $PSVersionTable

      - name: Install Pester
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module Pester -Scope CurrentUser -Force

      - name: gh auth (non-interactive)
        shell: pwsh
        run: |
          gh --version
          if (-not (gh auth status 2>$null)) {
            $env:GITHUB_TOKEN | gh auth login --with-token --hostname github.com
          }
          gh auth status

      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module Pester -Force
          $cfg = New-PesterConfiguration
          $cfg.Run.Path  = 'Tests'
          $cfg.Run.Exit  = $true          # 失敗で非 0 終了
          $cfg.Output.Verbosity = 'Detailed'
          $cfg.TestResult.Enabled      = $true
          $cfg.TestResult.OutputPath   = 'testResults.xml'
          $cfg.TestResult.OutputFormat = 'NUnitXml'
          Invoke-Pester -Configuration $cfg

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: testResults.xml
