name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pester:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure PowerShell
        shell: pwsh
        run: |
          Write-Host 'Using preinstalled PowerShell on the runner'
          $PSVersionTable

      - name: Install Pester
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module Pester -Scope CurrentUser -Force
          Import-Module Pester -PassThru | Format-List * | Out-Host

      - name: Verify gh auth
        shell: pwsh
        run: |
          gh --version
          gh auth status || ($env:GH_TOKEN | gh auth login --with-token)

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Path .\Tests -CI -Output Detailed
